### ISSUE TITLE
$KUBECONFIG permission denied as non root user

### ISSUE THREAD

**Issue by hoos** [kojak/autom8#10]
The installation process sets KUBECONFIG to /var/lib/openshift/openshift.local.config/master/admin.kubeconfig

As a non-root user one doesn't have access to the file by default. I had to copy the file to ~/.kube/config and export the new KUBECONFIG value for oc to work.

I tested the new configuration with an oc login.

**Comment by sbadakhc** [comment]
This is fixed in the latest release.
