### ISSUE TITLE
Missing OpenShift default templates

### ISSUE THREAD

**Issue by hoos** [kojak/autom8#11]
Just fucking fix it....

**Comment by hoos** [comment]
The problem seems to be related to missing roles/users. The system:admin user hasn't been set up with credentials and thus requests a password.

```
[root@master ~]# oc login -u system:admin --config /var/lib/openshift/openshift.local.config/master/admin.kubeconfig
Authentication required for https://master.example.com:8443 (openshift)
Username: system:admin
```
This inturn seems to break the downstream functinality required for automated installation of templates.

**Comment by sbadakhc** [comment]
This is fixed and and was related to an incorrect ip allocation.
