### ISSUE TITLE
Cannot read from remote repository

### ISSUE THREAD

**Issue by jackspyder** [kojak/autom8#17]
Attempted to deploy Centos nginx docker container and received the following error.

centos7-nginx:latest as a local directory pointing to a Git repository:  stat centos7-nginx:latest: no such file or directory

Errors occurred during resource creation:
error: no match for "nsecure-registry=true"

**Comment by sbadakhc** [comment]
This should be fixed in the latest release. Please test and reopen this issue if the problem persists.
