### ISSUE TITLE
Virtual Box Instructions - Prerequisites 

### ISSUE THREAD

**Issue by hoos** [kojak/autom8#2]
The documentation should note the requirement for a network connection to be configured in Virtual Box before the installation of the CentOS Minimal Image.

**Comment by sbadakhc** [comment]
I have updated the README.md with better instructions regarding the steps involved and the assumptions made about the vm but specific instructions concerning the virtualbox are out o f the scope of this project. The assumption is that you have created the vm in accordance with the minimum specifications and configuration options in the instructions.
