### ISSUE TITLE
Long pause after odd error message

### ISSUE THREAD

**Issue by hoos** [kojak/autom8#4]
Removed:
  NetworkManager.x86_64 1:1.8.0-9.el7        NetworkManager-libnm.x86_64 1:1.8.0-9.el7    NetworkManager-team.x86_64 1:1.8.0-9.el7
  NetworkManager-tui.x86_64 1:1.8.0-9.el7    NetworkManager-wifi.x86_64 1:1.8.0-9.el7

Complete!
Failed to execute operation: No such file or directory <---------------------WTF
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.coreix.net
 * extras: mirror.freethought-internet.co.uk
 * updates: mirror.sov.uk.goscomb.net
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-9 will be installed
--> Finished Dependency Resolution

**Comment by sbadakhc** [comment]
This is due to a download of packages. Its fixed in the latest version.
