### ISSUE TITLE
Long pause possibly infinite loop after error message 

### ISSUE THREAD

**Issue by hoos** [kojak/autom8#5]
Wrote master config to: openshift.local.config/master/master-config.yaml
./autom8: line 208: /root/workspace/autom8/cfg/master-config.yaml: No such file or directory
sed: can't read /var/lib/openshift/openshift.local.config/master/master-config.yaml: No such file or directory
cp: cannot stat ‘/root/workspace/autom8/certs/*’: No such file or directory
Adding password for user admin
Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.  <------------------- Hangs here until a CRTL-C and resumes without issue

**Comment by sbadakhc** [comment]
Fixed in latest...
